apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: labuk-kafka
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      auto.create.topics.enable: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: "256Mi"
        limits:
          memory: "512Mi"
    userOperator:
      resources:
        requests:
          memory: "256Mi"
        limits:
          memory: "512Mi"

---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: labuk-kafka
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: labuk-kafka
spec:
  replicas: 1
  roles:
    - broker  # Kafka broker role
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"